/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCCOMPLEXE_H_RPCGEN
#define _CALCCOMPLEXE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct complexe {
	int pentiere;
	float pimaginaire;
};
typedef struct complexe complexe;

#define CALCCOMPPROG 0x30090949
#define CALCVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define INIT 1
extern  struct complexe * init_1(complexe *, CLIENT *);
extern  struct complexe * init_1_svc(complexe *, struct svc_req *);
#define ADD 2
extern  struct complexe * add_1(complexe *, CLIENT *);
extern  struct complexe * add_1_svc(complexe *, struct svc_req *);
#define MUL 3
extern  struct complexe * mul_1(complexe *, CLIENT *);
extern  struct complexe * mul_1_svc(complexe *, struct svc_req *);
extern int calccompprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INIT 1
extern  struct complexe * init_1();
extern  struct complexe * init_1_svc();
#define ADD 2
extern  struct complexe * add_1();
extern  struct complexe * add_1_svc();
#define MUL 3
extern  struct complexe * mul_1();
extern  struct complexe * mul_1_svc();
extern int calccompprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_complexe (XDR *, complexe*);

#else /* K&R C */
extern bool_t xdr_complexe ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCCOMPLEXE_H_RPCGEN */
